# Generated by Django 5.2.10 on 2026-04-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townpulse_app', '0002_pendingsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingSignup',
        ),
    ]
